### ISSUE TITLE
Unhandled Promise-like classes (non-subclassed) suppress middleware output (ZoneAwarePromise)

### ISSUE THREAD

**Issue by rlmestre** [wooorm/trough#12]
`trough` is a transitive dependency of Astro's MDX plugin (and possibly others). When combining Astro and Angular using [AnalogJS's plugin](https://github.com/analogjs/analog), Markdown parsing breaks due to Zone.js patches on the server.

`trough` specifically checks if the result of a transformer is an instance of a Promise [here](https://github.com/wooorm/trough/blob/787d92eb2d37ccc60c80cd656d74ac3b967da2d6/index.js#L131). Zone.js replaces the native Promise class with a ZoneAwarePromise, which is not a subclass and fails this check.

https://github.com/wooorm/trough/blob/787d92eb2d37ccc60c80cd656d74ac3b967da2d6/index.js#L130-L138

The results are then omitted due to the Promise not resolving, suppressing the output or preventing the next plugin from parsing correctly. This could be fixed by processing other "thenables":

```diff
 if (!fnExpectsCallback) { 
-   if (result instanceof Promise) { 
+   if (result instanceof Promise || result && 'then' in result) { 
     result.then(then, done) 
   } else if (result instanceof Error) { 
     done(result) 
   } else { 
     then(result) 
   } 
 } 
```
Unfortunately there are no workarounds to consider here because Zone.js is required in the global scope for Angular apps.

Related:
analogjs/analog#849, analogjs/analog#690, withastro/astro#8611

**Comment by wooorm** [comment]
a) libraries should stop meddling with the global scope, what year is this?
b) instanceof is brittle in plain JavaScript too, when working with different frames or workers or different versions of packages exposing classes, so fine to start duck typing
c) I don't see a need to do both. A thenable is fine, and is a known concept in the promise space
d) test would be nice!

**Comment by wooorm** [comment]
Solved!
